sudo: required

services:
  - docker

before_script:
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml up -d

script:
  - docker-compose exec web sh -c "pipenv install -d tox"
  - docker-compose exec web sh -c "pipenv run tox"

after_script:
  - docker-compose -f docker-compose.yml -f docker-compose.travis.yml down
