version: '3'

services:
  db:
    image: postgres:10-alpine
  web:
    build: ./
    tty: true
    environment:
      - USE_HOT_RELOAD=${USE_HOT_RELOAD-true}
      - DJANGO_INSTALL_PATH=/code/
      - DJANGO_SETTINGS_MODULE=sflvault_server.settings.dev
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
